package concepts.dyn.primitives.special;

import concepts.StatCptEnum;
import concepts.dyn.primitives.*;

/**
 * An empty primitive with a special meaning of being an elementary premise, 
 * i.e. a premise of the terminal level. Can be named, if it is must be known to the code,
 * or unnamed, if it is generated by Chris. Than its meaning is just its cid. What does
 * actually that cid means is known to Chris by its interconnections with other concepts.
 * @author su
 */
public class BasicPremise extends MarkedNil {

    /** 
     * Constructor.
     */ 
    public BasicPremise() { 
        super(StatCptEnum.Mrk_BasicPremise.ordinal());
    } 
}
